export const pairsToExchangeMapping: { [key: string]: string } = {
  ETHUSDT: 'BINANCE:ETHUSDT',
  ETHDAI: 'COINBASE:ETHDAI',
  ETHUSD: 'COINBASE:ETHUSD',
  ETHBUSD: 'BINANCE:ETHBUSD',
  ETHGUSD: 'GEMINI:ETHGUSD',
  ETHBTC: 'BINANCE:ETHBTC',
  USDTDAI: 'BINANCE:USDTDAI',
  USDTUSDC: 'COINBASE:USDTUSDC',
  USDTBUSD: 'UNISWAP3ETH:USDTBUSD',
  USDTGUSD: 'UNISWAP3ETH:USDTGUSD',
  USDTWBTC: 'UNISWAP3ETH:USDTWBTC',
  USDTETH: 'UNISWAP3ETH:USDTETH',
};
